sudo: required
language: python
git:
  depth: 10
  quiet: true
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      python: "3.6"
      script:
        - set -v  # print commands as they're executed
        - set -e  # fail and exit on any command erroring
        - rm -rf uncertainty_baselines.egg-info/
        - pylint --jobs=2 --rcfile=pylintrc *.py
        - pylint --jobs=2 --rcfile=pylintrc */
python:
  - "3.6"
env:
  matrix:
    - TF_VERSION="tensorflow"
    - TF_VERSION="tf-nightly"
install:
  - set -v  # print commands as they're executed
  - set -e  # fail and exit on any command erroring
  # Ensure that the base dependencies are sufficient for a full import.
  # Install backend and test dependencies.
  - |
    if [[ "$TF_VERSION" == "tf-nightly"  ]]; then
      pip install -q -e .[tests,tf-nightly]
    else
      pip install -q -e .[tests]
    fi
  - python -c "import uncertainty_baselines as ub"

script:
  - set -v  # print commands as they're executed
  - set -e  # fail and exit on any command erroring
  - python -m unittest discover -s . -p '*_test.py'
